output "available_azs" {
  description = "available zones"
  value = data.aws_availability_zones.available.names
}

output "zookeeper_connect_string" {
  value = aws_msk_cluster.example.zookeeper_connect_string
}

output "bootstrap_brokers" {
  description = "Plaintext connection host:port pairs"
  value       = aws_msk_cluster.example.bootstrap_brokers
}

output "bootstrap_brokers_tls" {
  description = "TLS connection host:port pairs"
  value       = aws_msk_cluster.example.bootstrap_brokers_tls
}

output "producer_public_ip" {
  description = "Public ip for producer ec2"
  value       = aws_instance.producer.public_ip
}

output "consumer_public_ip" {
  description = "Public ip for consumer ec2"
  value       = aws_instance.consumer.public_ip
}

//output "cluster_endpoint" {
//  description = "Endpoint for EKS control plane."
//  value       = module.eks.cluster_endpoint
//}
//
//output "cluster_security_group_id" {
//  description = "Security group ids attached to the cluster control plane."
//  value       = module.eks.cluster_security_group_id
//}
//
//output "kubectl_config" {
//  description = "kubectl config as generated by the module."
//  value       = module.eks.kubeconfig
//}
//
//output "config_map_aws_auth" {
//  description = "A kubernetes configuration to authenticate to this EKS cluster."
//  value       = module.eks.config_map_aws_auth
//}

//output "region" {
//  description = "AWS region."
//  value       = var.region
//}
